"""baseline schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-27 00:53:06.010064
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql  # noqa: F401

import app.db  # noqa: F401  (custom column types)
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('actor_name', sa.String(length=200), nullable=False),
    sa.Column('actor_role', sa.String(length=20), nullable=False),
    sa.Column('facility_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('patient_code', sa.String(length=20), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_facility_id'), 'audit_events', ['facility_id'], unique=False)
    op.create_index(op.f('ix_audit_events_patient_code'), 'audit_events', ['patient_code'], unique=False)
    op.create_index(op.f('ix_audit_events_ts'), 'audit_events', ['ts'], unique=False)
    op.create_table('facilities',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('languages', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('specialists', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('referral_destination', sa.String(length=300), nullable=False),
    sa.Column('beds_total', sa.Integer(), nullable=False),
    sa.Column('beds_occupied', sa.Integer(), nullable=False),
    sa.Column('offline_mode', sa.Boolean(), nullable=False),
    sa.Column('capabilities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otp_challenges',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('code_hash', sa.String(length=200), nullable=False),
    sa.Column('expires_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_challenges_phone'), 'otp_challenges', ['phone'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=1), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('village', sa.String(length=120), nullable=True),
    sa.Column('employer_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_code'), 'patients', ['code'], unique=True)
    op.create_index(op.f('ix_patients_phone'), 'patients', ['phone'], unique=False)
    op.create_table('revoked_tokens',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('revoked_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_table('cohorts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('employer_name', sa.String(length=200), nullable=False),
    sa.Column('screening_type', sa.String(length=200), nullable=False),
    sa.Column('facility_id', sa.String(length=64), nullable=True),
    sa.Column('workers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('proxy_name', sa.String(length=200), nullable=True),
    sa.Column('proxy_relation', sa.String(length=64), nullable=True),
    sa.Column('privacy_context', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('scopes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('captured_by', sa.String(length=200), nullable=False),
    sa.Column('captured_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consents_patient_id'), 'consents', ['patient_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('facility_id', sa.String(length=64), nullable=False),
    sa.Column('bound_by', sa.String(length=200), nullable=False),
    sa.Column('bound_by_id', sa.String(length=64), nullable=True),
    sa.Column('bound_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminders',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('due_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('channel', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_patient_id'), 'reminders', ['patient_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('facility_id', sa.String(length=64), nullable=True),
    sa.Column('registration_no', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('encounters',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('facility_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('urgency', sa.String(length=8), nullable=False),
    sa.Column('rules_urgency', sa.String(length=8), nullable=False),
    sa.Column('urgency_source', sa.String(length=10), nullable=False),
    sa.Column('note', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('intake', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('override', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('reviewed_by', sa.String(length=200), nullable=True),
    sa.Column('reviewed_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('referral_needed', sa.Boolean(), nullable=True),
    sa.Column('specialist_required', sa.String(length=32), nullable=True),
    sa.Column('escalation_due_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('consent_id', sa.String(length=64), nullable=True),
    sa.Column('client_ref', sa.String(length=80), nullable=False),
    sa.Column('token', sa.String(length=12), nullable=True),
    sa.Column('token_date', sa.String(length=10), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['consent_id'], ['consents.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_ref')
    )
    op.create_index(op.f('ix_encounters_created_at'), 'encounters', ['created_at'], unique=False)
    op.create_index(op.f('ix_encounters_facility_id'), 'encounters', ['facility_id'], unique=False)
    op.create_index(op.f('ix_encounters_patient_id'), 'encounters', ['patient_id'], unique=False)
    op.create_index(op.f('ix_encounters_status'), 'encounters', ['status'], unique=False)
    op.create_index(op.f('ix_encounters_token_date'), 'encounters', ['token_date'], unique=False)
    op.create_table('kiosk_links',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('facility_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('sessions', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kiosk_links_code'), 'kiosk_links', ['code'], unique=True)
    op.create_table('user_pins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('pin_hash', sa.String(length=200), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_id')
    )
    op.create_table('escalations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('encounter_id', sa.String(length=64), nullable=False),
    sa.Column('raised_by', sa.String(length=200), nullable=False),
    sa.Column('raised_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('to_role', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('auto', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=200), nullable=True),
    sa.Column('acknowledged_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('ack_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalations_encounter_id'), 'escalations', ['encounter_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('encounter_id', sa.String(length=64), nullable=True),
    sa.Column('storage_key', sa.String(length=255), nullable=True),
    sa.Column('uploaded_by', sa.String(length=64), nullable=True),
    sa.Column('uploaded_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('purged_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('sample_key', sa.String(length=32), nullable=True),
    sa.Column('boxes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_encounter_id'), 'files', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_files_expires_at'), 'files', ['expires_at'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('encounter_id', sa.String(length=64), nullable=False),
    sa.Column('destination', sa.String(length=300), nullable=False),
    sa.Column('specialty', sa.String(length=120), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('transport', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_encounter_id'), 'referrals', ['encounter_id'], unique=False)
    op.create_table('share_links',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('code_hash', sa.String(length=200), nullable=False),
    sa.Column('encounter_id', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_links_encounter_id'), 'share_links', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_share_links_token'), 'share_links', ['token'], unique=True)
    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        # Database-level guarantee that the audit log is append-only.
        op.execute(app.db.APPEND_ONLY_SQL)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_share_links_token'), table_name='share_links')
    op.drop_index(op.f('ix_share_links_encounter_id'), table_name='share_links')
    op.drop_table('share_links')
    op.drop_index(op.f('ix_referrals_encounter_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_files_expires_at'), table_name='files')
    op.drop_index(op.f('ix_files_encounter_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_escalations_encounter_id'), table_name='escalations')
    op.drop_table('escalations')
    op.drop_table('user_pins')
    op.drop_index(op.f('ix_kiosk_links_code'), table_name='kiosk_links')
    op.drop_table('kiosk_links')
    op.drop_index(op.f('ix_encounters_token_date'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_status'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_patient_id'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_facility_id'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_created_at'), table_name='encounters')
    op.drop_table('encounters')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_reminders_patient_id'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_table('devices')
    op.drop_index(op.f('ix_consents_patient_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_table('cohorts')
    op.drop_table('revoked_tokens')
    op.drop_index(op.f('ix_patients_phone'), table_name='patients')
    op.drop_index(op.f('ix_patients_code'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_otp_challenges_phone'), table_name='otp_challenges')
    op.drop_table('otp_challenges')
    op.drop_table('facilities')
    op.drop_index(op.f('ix_audit_events_ts'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_patient_code'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_facility_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
