"""organisations directory fitness

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-27 00:54:50.156243
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql  # noqa: F401

import app.db  # noqa: F401  (custom column types)
from sqlalchemy.dialects import postgresql

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility_directory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ref', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('name_local', sa.String(length=300), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('ownership', sa.String(length=10), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('beds', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref')
    )
    op.create_index(op.f('ix_facility_directory_kind'), 'facility_directory', ['kind'], unique=False)
    op.create_index(op.f('ix_facility_directory_name'), 'facility_directory', ['name'], unique=False)
    op.create_index(op.f('ix_facility_directory_pincode'), 'facility_directory', ['pincode'], unique=False)
    op.create_index('ix_facility_directory_state_district', 'facility_directory', ['state', 'district'], unique=False)
    op.create_table('organisations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('registration_no', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('contact_phone', sa.String(length=15), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fitness_assessments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('organisation_id', sa.String(length=64), nullable=False),
    sa.Column('encounter_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('restrictions', sa.String(length=300), nullable=True),
    sa.Column('valid_until', sa.String(length=10), nullable=True),
    sa.Column('assessed_by', sa.String(length=200), nullable=False),
    sa.Column('assessed_by_id', sa.String(length=64), nullable=True),
    sa.Column('assessed_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fitness_assessments_organisation_id'), 'fitness_assessments', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_fitness_assessments_patient_id'), 'fitness_assessments', ['patient_id'], unique=False)
    op.add_column('facilities', sa.Column('source', sa.String(length=16), server_default='sample', nullable=False))
    op.add_column('facilities', sa.Column('directory_ref', sa.String(length=40), nullable=True))
    op.add_column('facilities', sa.Column('organisation_id', sa.String(length=64), nullable=True))
    op.add_column('facilities', sa.Column('verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('facilities', sa.Column('pincode', sa.String(length=10), nullable=True))
    op.add_column('facilities', sa.Column('address', sa.String(length=300), nullable=True))
    op.add_column('facilities', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('facilities', sa.Column('lon', sa.Float(), nullable=True))
    op.add_column('facilities', sa.Column('created_by', sa.String(length=64), nullable=True))
    op.add_column('facilities', sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_facilities_organisation_id'), 'facilities', ['organisation_id'], unique=False)
    op.create_unique_constraint('uq_facilities_directory_ref', 'facilities', ['directory_ref'])
    op.create_foreign_key('fk_facilities_organisation', 'facilities', 'organisations', ['organisation_id'], ['id'])
    op.add_column('otp_challenges', sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=True))
    op.add_column('otp_challenges', sa.Column('ip', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_otp_challenges_created_at'), 'otp_challenges', ['created_at'], unique=False)
    op.create_index(op.f('ix_otp_challenges_ip'), 'otp_challenges', ['ip'], unique=False)
    op.add_column('patients', sa.Column('organisation_id', sa.String(length=64), nullable=True))
    op.add_column('patients', sa.Column('employee_code', sa.String(length=40), nullable=True))
    op.add_column('patients', sa.Column('department', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_patients_organisation_id'), 'patients', ['organisation_id'], unique=False)
    op.create_unique_constraint('uq_patient_employee_code', 'patients', ['organisation_id', 'employee_code'])
    op.create_foreign_key('fk_patients_organisation', 'patients', 'organisations', ['organisation_id'], ['id'])
    op.add_column('users', sa.Column('organisation_id', sa.String(length=64), nullable=True))
    op.create_foreign_key('fk_users_organisation', 'users', 'organisations', ['organisation_id'], ['id'])
    # ### end Alembic commands ###
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        # Fuzzy, typo-tolerant facility search.
        op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
        op.execute("CREATE INDEX IF NOT EXISTS ix_facility_directory_name_trgm ON facility_directory USING gin (lower(name) gin_trgm_ops)")
    _convert_sample_cohorts(bind)
    op.drop_table("cohorts")


def _convert_sample_cohorts(bind) -> None:
    """Old installs kept employer cohorts as JSON. Turn them into an organisation, worker patients and
    fitness assessments so the employer view keeps working on real tables."""
    import json
    from datetime import datetime, timezone

    rows = bind.execute(sa.text("SELECT id, employer_name, facility_id, workers FROM cohorts")).mappings().all()
    if not rows:
        return
    now = datetime.now(timezone.utc)
    orgs: dict[str, str] = {}
    for c in rows:
        fid = c["facility_id"]
        if fid not in orgs:
            fac = bind.execute(sa.text("SELECT state, district FROM facilities WHERE id = :f"), {"f": fid}).mappings().first()
            org_id = f"org_{(fid or 'sample')[4:][:40]}"
            bind.execute(
                sa.text("INSERT INTO organisations (id, name, kind, state, district, verified, created_at) VALUES (:id, :n, 'industrial', :s, :d, false, :t)"),
                {"id": org_id, "n": c["employer_name"], "s": fac["state"] if fac else "", "d": fac["district"] if fac else "", "t": now},
            )
            bind.execute(sa.text("UPDATE facilities SET organisation_id = :o, source = 'organisation' WHERE id = :f"), {"o": org_id, "f": fid})
            bind.execute(sa.text("UPDATE users SET organisation_id = :o WHERE role = 'employer' AND facility_id = :f"), {"o": org_id, "f": fid})
            orgs[fid] = org_id
        org_id = orgs[fid]
        workers = c["workers"] if isinstance(c["workers"], list) else json.loads(c["workers"] or "[]")
        for w in workers:
            code = w["worker_code"]
            pid = f"pat_w_{code.lower().replace('-', '_')}"
            bind.execute(
                sa.text(
                    "INSERT INTO patients (id, code, name, age, sex, phone, language, category, organisation_id, employee_code, department, created_at) "
                    "VALUES (:id, :code, :name, 30, 'M', NULL, 'or', 'normal', :o, :e, :dep, :t) ON CONFLICT DO NOTHING"
                ),
                {"id": pid, "code": f"JVA-{code}"[:20], "name": f"Worker {code} (sample)", "o": org_id, "e": code, "dep": w.get("department"), "t": now},
            )
            if w.get("fitness_status") and w["fitness_status"] != "pending_review":
                bind.execute(
                    sa.text(
                        "INSERT INTO fitness_assessments (id, patient_id, organisation_id, status, assessed_by, assessed_at) "
                        "VALUES (:id, :p, :o, :s, 'Occupational Health Physician (sample)', :t)"
                    ),
                    {"id": f"fit_{pid[6:]}"[:64], "p": pid, "o": org_id, "s": w["fitness_status"], "t": w.get("last_screened_at") or now},
                )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_users_organisation', 'users', type_='foreignkey')
    op.drop_column('users', 'organisation_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_patients_organisation', 'patients', type_='foreignkey')
    op.drop_constraint('uq_patient_employee_code', 'patients', type_='unique')
    op.drop_index(op.f('ix_patients_organisation_id'), table_name='patients')
    op.drop_column('patients', 'department')
    op.drop_column('patients', 'employee_code')
    op.drop_column('patients', 'organisation_id')
    op.drop_index(op.f('ix_otp_challenges_ip'), table_name='otp_challenges')
    op.drop_index(op.f('ix_otp_challenges_created_at'), table_name='otp_challenges')
    op.drop_column('otp_challenges', 'ip')
    op.drop_column('otp_challenges', 'created_at')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_facilities_organisation', 'facilities', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('uq_facilities_directory_ref', 'facilities', type_='unique')
    op.drop_index(op.f('ix_facilities_organisation_id'), table_name='facilities')
    op.drop_column('facilities', 'created_at')
    op.drop_column('facilities', 'created_by')
    op.drop_column('facilities', 'lon')
    op.drop_column('facilities', 'lat')
    op.drop_column('facilities', 'address')
    op.drop_column('facilities', 'pincode')
    op.drop_column('facilities', 'verified')
    op.drop_column('facilities', 'organisation_id')
    op.drop_column('facilities', 'directory_ref')
    op.drop_column('facilities', 'source')
    op.create_table('cohorts',
    sa.Column('id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('employer_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('screening_type', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('facility_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('workers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('cohorts_facility_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cohorts_pkey'))
    )
    op.drop_index(op.f('ix_fitness_assessments_patient_id'), table_name='fitness_assessments')
    op.drop_index(op.f('ix_fitness_assessments_organisation_id'), table_name='fitness_assessments')
    op.drop_table('fitness_assessments')
    op.drop_table('organisations')
    op.drop_index('ix_facility_directory_state_district', table_name='facility_directory')
    op.drop_index(op.f('ix_facility_directory_pincode'), table_name='facility_directory')
    op.drop_index(op.f('ix_facility_directory_name'), table_name='facility_directory')
    op.drop_index(op.f('ix_facility_directory_kind'), table_name='facility_directory')
    op.drop_table('facility_directory')
    # ### end Alembic commands ###
