"""account pin second factor

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-27 08:13:23.066647
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql  # noqa: F401

import app.db  # noqa: F401  (custom column types)
from sqlalchemy.dialects import postgresql

revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_pins')
    op.add_column('users', sa.Column('pin_hash', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('pin_set_at', app.db.UTCDateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('pin_failed_attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('pin_locked_until', app.db.UTCDateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    # Sample walkthrough accounts get the documented sample PIN; real accounts create their own PIN
    # at their next sign-in (after phone OTP).
    from datetime import datetime, timezone

    from app.config import get_settings
    from app.security import PIN_ROLES, hash_pin

    s = get_settings()
    phones = [p.strip() for p in s.demo_phones.split(",") if p.strip()]
    bind = op.get_bind()
    rows = bind.execute(sa.text("SELECT id, role, phone FROM users WHERE pin_hash IS NULL")).mappings().all()
    for r in rows:
        if r["role"] in PIN_ROLES and r["phone"] in phones:
            bind.execute(
                sa.text("UPDATE users SET pin_hash = :h, pin_set_at = :t WHERE id = :id"),
                {"h": hash_pin(s.demo_pin, r["id"]), "t": datetime.now(timezone.utc), "id": r["id"]},
            )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pin_locked_until')
    op.drop_column('users', 'pin_failed_attempts')
    op.drop_column('users', 'pin_set_at')
    op.drop_column('users', 'pin_hash')
    op.create_table('user_pins',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('pin_hash', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('failed_attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_pins_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pins_pkey')),
    sa.UniqueConstraint('user_id', 'device_id', name=op.f('user_pins_user_id_device_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
