"""email verification

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-30 00:22:55.261061
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql  # noqa: F401

import app.db  # noqa: F401  (custom column types)


revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_challenges', sa.Column('email', sa.String(length=254), nullable=True))
    op.add_column('otp_challenges', sa.Column('user_id', sa.String(length=64), nullable=True))
    op.alter_column('otp_challenges', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.create_index(op.f('ix_otp_challenges_email'), 'otp_challenges', ['email'], unique=False)
    op.add_column('users', sa.Column('email', sa.String(length=254), nullable=True))
    op.add_column('users', sa.Column('email_verified_at', app.db.UTCDateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('phone_verified', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'phone_verified')
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'email')
    op.drop_index(op.f('ix_otp_challenges_email'), table_name='otp_challenges')
    op.alter_column('otp_challenges', 'phone',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.drop_column('otp_challenges', 'user_id')
    op.drop_column('otp_challenges', 'email')
    # ### end Alembic commands ###
